const svgTransforms = {
  actionRedo: "translate(0 1)",
  actionUndo: "translate(0 1)",
  arrowBottom: "translate(1)",
  arrowLeft: "translate(0 1)",
  arrowRight: "translate(0 1)",
  arrowThickBottom: "translate(1)",
  arrowThickLeft: "translate(0 1)",
  arrowThickRight: "translate(0 1)",
  arrowThickTop: "translate(1)",
  arrowTop: "translate(1)",
  audio: "translate(0 1)",
  badge: "translate(2)",
  batteryEmpty:"translate(0 1)",
  batteryFull: "translate(0 1)",
  bluetooth: "translate(1)",
  bolt: "translate(1)",
  bookmark: "translate(2)",
  britishPound: "translate(1)",
  caretBottom: "translate(0 2)",
  caretLeft: "translate(2)",
  caretRight: "translate(2)",
  caretTop: "translate(0 2)",
  cart: "translate(0 1)",
  check: "translate(0 1)",
  chevronBottom: "translate(0 1)",
  chevronLeft: "translate(1)",
  chevronRight: "translate(1)",
  chevronTop: "translate(0 1)",
  cloud: "translate(0 1)",
  code: "translate(0 1)",
  creditCard: "translate(0 1)",
  delete: "translate(0 1)",
  dial: "translate(0 1)",
  dollar: "translate(1)",
  doubleQuoteSansLeft: "translate(0 1)",
  doubleQuoteSansRight: "translate(0 1)",
  doubleQuoteSerifLeft: "translate(0 1)",
  doubleQuoteSerifRight: "translate(0 1)",
  droplet: "translate(1)",
  elevator: "translate(1)",
  ellipses: "translate(0 3)",
  envelopeClosed: "translate(0 1)",
  euro: "translate(-1)",
  eye: "translate(0 1)",
  flash: "translate(2)",
  heart: "translate(0 1)",
  infinity: "translate(0 2)",
  info: "translate(2)",
  laptop:  "translate(0 1)",
  lightbulb: "translate(1)",
  lockLocked: "translate(1)",
  lockUnlocked: "translate(1)",
  loopCircular: "translate(0 1)",
  mapMarker: "translate(1)",
  mediaPause: "translate(1 1)",
  mediaPlay: "translate(1 1)",
  mediaRecord: "translate(1 1)",
  mediaSkipBackward: "translate(0 1)",
  mediaSkipForward: "translate(0 1)",
  mediaStepBackward: "translate(0 1)",
  mediaStepForward: "translate(0 1)",
  mediaStop:"translate(1 1)",
  menu: "translate(0 1)",
  microphone: "translate(1)",
  minus: "translate(0 3)",
  phone: "translate(1)",
  questionMark: "translate(2)",
  resizeHeight: "translate(1)",
  resizeWidth: "translate(0 1)",
  tags: "translate(0 1)",
  video:"translate(0 1)",
  volumeLow: "translate(1)",
  volumeOff: "translate(2)",
}

export default svgTransforms
